version: '3'
services:
      
    ntopng:
        image: vimagick/ntopng
        command: --community -d /var/lib/ntopng -i wlp2s0  -r 127.0.0.1:6379@0 -w 0.0.0.0:3410
        volumes:
           - ./data/ntopng:/var/lib/ntopng
        network_mode: host
        restart: unless-stopped

    redis:
        image: redis:alpine
        command: --save 900 1
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: unless-stopped
